# Generated by Django 5.1.5 on 2025-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isBio',
            field=models.BooleanField(default=False),
        ),
    ]
